export const en = {
  app: {
    name: "DevBoard",
    metadata: {
      title: "Create Next App",
      description: "Generated by create next app",
    },
  },

  // ─── Auth Feature ───────────────────────────────────────────────
  auth: {
    signIn: {
      title: "Welcome back!",
      description: "Login to access your projects and dashboard.",
      emailLabel: "Email address",
      emailPlaceholder: "Email address",
      passwordLabel: "Password",
      passwordPlaceholder: "Password",
      submitButton: "Login",
      submitButtonLoading: "Logging in...",
      footer: "Don't have an account?",
      footerLink: "Sign Up",
      toastSuccess: "Logged in successfully!",
      toastErrorFallback: "Invalid credentials",
    },
    signUp: {
      title: "Sign up",
      description: "By signing up, you agree to our",
      privacyPolicyLink: "Privacy Policy",
      termsLink: "Terms of Service",
      nameLabel: "Name",
      namePlaceholder: "Enter your name",
      emailLabel: "Email address",
      emailPlaceholder: "Email address",
      passwordLabel: "Password",
      passwordPlaceholder: "Password",
      submitButton: "Sign up",
      submitButtonLoading: "Signing up...",
      footer: "Already have an account?",
      footerLink: "Sign In",
      toastSuccess: "Account created successfully! Logging you in...",
      autoLoginError:
        "Account created, but login failed. Please sign in manually.",
      toastErrorFallback: "Registration failed",
    },
    socialAuth: {
      loginGoogle: "Login with Google",
      loginGithub: "Login with GitHub",
      signupGoogle: "Sign up with Google",
      signupGithub: "Sign up with GitHub",
    },
    signOut: {
      button: "Sign out",
    },
    layout: {
      signUpToggle: "Sign Up",
      loginToggle: "Login",
    },
  },

  // ─── Dashboard / Navigation ─────────────────────────────────────
  dashboard: {
    navbar: {
      brandName: "DevBoard",
      logOut: "Log out",
      toggleSidebar: "Toggle sidebar",
      avatarFallback: "U",
    },
    sidebar: {
      brandName: "DevBoard",
      closeSidebar: "Close sidebar",
    },
    navigation: {
      home: "Home",
      myTasks: "My Tasks",
      settings: "Settings",
      members: "Members",
    },
  },

  // ─── Workspace Feature ──────────────────────────────────────────
  workspace: {
    switcher: {
      sectionTitle: "Workspaces",
      createTooltip: "Create Workspace",
      loadingPlaceholder: "Loading...",
      selectPlaceholder: "Select workspace",
      noWorkspaces: "No workspaces",
      defaultRole: "member",
    },
    form: {
      createTitle: "Create a new workspace",
      createDescription:
        "Workspaces are shared environments where team members can collaborate on projects.",
      nameLabel: "Workspace Name",
      namePlaceholder: "Enter workspace name",
      logoLabel: "Workspace Logo",
      logoOptional: "(Optional)",
      cancelButton: "Cancel",
      signOutButton: "Sign out",
      createButton: "Create Workspace",
      saveButton: "Save Changes",
      creatingButton: "Creating...",
      savingButton: "Saving...",
      uploadingButton: "Uploading logo...",
      toastCreateSuccess: "Workspace created successfully!",
      toastCreateError: "Failed to create workspace",
      toastUpdateSuccess: "Workspace updated successfully!",
      toastUpdateError: "Failed to update workspace",
      toastDeleteSuccess: "Workspace deleted successfully!",
      toastDeleteError: "Failed to delete workspace",
      toastUploadError: "Failed to upload logo.",
      toastUploadErrorRetry: "Failed to upload logo. Please try again.",
    },
    createDialog: {
      title: "Create Workspace",
      nameLabel: "Workspace Name",
      namePlaceholder: "Enter workspace name",
      logoLabel: "Workspace Logo",
      logoOptional: "(Optional)",
      logoHint: "PNG, JPEG (Max 1MB compressed)",
      createButton: "Create Workspace",
      uploadingButton: "Uploading logo...",
      creatingButton: "Creating workspace...",
      toastSuccess: "Workspace created!",
      toastError: "Failed to create workspace",
      toastImageError: "Please select a PNG or JPEG image.",
      toastProcessError: "Failed to process image. Please try again.",
    },
    logoUploader: {
      label: "Workspace Logo",
      optional: "(Optional)",
      selectImage: "Select image",
      changeLogo: "Change logo",
      compressing: "Compressing...",
      remove: "Remove",
      hint: "PNG, JPEG (Drag and drop or select up to 1MB compressed)",
      toastInvalidType: "Please select a PNG or JPEG image.",
      toastProcessError: "Failed to process image. Please try again.",
      previewAlt: "Logo preview",
    },
    dangerZone: {
      title: "Danger Zone",
      description:
        "Permanently delete this workspace and all associated projects and data. This action cannot be undone.",
      deleteButton: "Delete Workspace",
      deletingButton: "Deleting...",
      confirmTitle: "Delete Workspace",
      confirmDescription: "Are you sure you want to proceed?",
      confirmButton: "Delete Workspace",
    },
    collaboration: {
      title: "Members & Collaboration",
      description:
        "Invite new members to collaborate on projects and manage team access.",
      inviteButton: "Invite Member",
    },

    // ─── Settings Page ──────────────────────────────────────────
    settingsPage: {
      title: "Workspace Settings",
      description:
        "Update workspace settings, manage appearance, or delete workspace.",
      accessDeniedTitle: "Access Denied",
      accessDeniedDescription:
        "You do not have permission to manage settings for this workspace.",
    },

    // ─── Overview Page ──────────────────────────────────────────
    overviewPage: {
      title: "Overview",
      welcomePrefix: "Welcome to",
      welcomeSuffix: "dashboard overview.",
    },

    // ─── Members ────────────────────────────────────────────────
    members: {
      pageTitle: "Workspace Members",
      pageDescription:
        "Manage roles, update collaboration permissions, or remove team members.",
      errorTitle: "Error Loading Members",
      errorDefault: "Failed to load workspace members",
      roleLabel: "Role",
      youBadge: "You",
      anonymousUser: "Anonymous User",
      avatarFallback: "MB",
      removeTooltip: "Remove member",
      roles: {
        owner: "Owner",
        admin: "Admin",
        member: "Member",
        ownerTransfer: "Owner (Transfer)",
      },
      toastRoleSuccess: "Member role updated successfully!",
      toastRoleError: "Failed to update role",
      toastRemoveSuccess: "removed from workspace.",
      toastRemoveSuccessFallback: "Member",
      toastRemoveError: "Failed to remove member",
      removeConfirm: {
        title: "Remove Member",
        confirmButton: "Remove Member",
        confirmLoadingButton: "Removing...",
      },
      transferConfirm: {
        title: "Transfer Workspace Ownership",
        confirmButton: "Transfer Ownership",
        confirmLoadingButton: "Transferring...",
      },
    },

    // ─── Invite ─────────────────────────────────────────────────
    invite: {
      dialog: {
        title: "Invite Team Member",
        emailLabel: "Email Address",
        emailPlaceholder: "name@example.com",
        roleLabel: "Role",
        rolePlaceholder: "Select role",
        roleMember: "Member",
        roleAdmin: "Admin",
        generateButton: "Generate Invite",
        generatingButton: "Generating...",
        toastSuccess: "Invitation generated successfully!",
        toastError: "Failed to generate invitation link",
        toastErrorMember: "This user is already a member.",
        toastErrorPermission: "You do not have permission to invite members.",
        toastErrorDefault: "Failed to invite member. Please try again.",
      },
      generatedView: {
        title: "Invite Link Generated",
        description:
          "Copy and share this unique link with the user to invite them to this workspace. It expires in 7 days.",
        copyButton: "Copy Link",
        copiedButton: "Copied",
        doneButton: "Done",
        toastCopied: "Invite link copied to clipboard!",
      },
      accept: {
        title: "Accept Invitation",
        declineButton: "Decline",
        acceptButton: "Accept Invite",
        acceptingButton: "Accepting...",
        footer:
          "By accepting, you will gain access to this workspace and its resources.",
        invitedEmailLabel: "Invited email",
        toastSuccess: "Joined workspace successfully!",
        toastError: "Failed to accept invite",
        toastErrorGeneric: "Something went wrong. Please try again.",
      },
      unauthenticated: {
        signInButton: "Sign In",
        createAccountButton: "Create Account",
        footer: "Please log in or sign up with the invited email to accept.",
      },
      mismatch: {
        title: "Account Mismatch",
        signOutButton: "Sign out and try again",
        backButton: "Back to Dashboard",
      },
      errors: {
        default: {
          title: "Invalid Invitation",
          description: "This invitation link is invalid or has expired.",
        },
        NOT_FOUND: {
          title: "Invite link invalid",
          description:
            "The invitation token you used does not exist. Please check the URL and try again.",
        },
        REVOKED: {
          title: "Invitation revoked",
          description:
            "This invitation has been revoked by the workspace administrator.",
        },
        EXPIRED: {
          title: "Invitation expired",
          description:
            "This invitation has expired. Please request a new invite link from the workspace owner.",
        },
        ALREADY_ACCEPTED: {
          title: "Already a member",
        },
        goToDashboard: "Go to Dashboard",
        returnToDashboard: "Return to Dashboard",
      },
    },
  },

  project: {
    switcher: {
      sectionTitle: "Projects",
      createTooltip: "Create Project",
      loadingPlaceholder: "Loading...",
      selectPlaceholder: "Select project",
      noProjects: "No projects",
    },
    createDialog: {
      title: "Create Project",
      nameLabel: "Project Name",
      namePlaceholder: "Enter project name",
      logoLabel: "Project Logo",
      logoOptional: "(Optional)",
      logoHint: "PNG, JPEG (Max 1MB compressed)",
      createButton: "Create Project",
      uploadingButton: "Uploading logo...",
      creatingButton: "Creating project...",
      toastSuccess: "Project created!",
      toastError: "Failed to create project",
      toastImageError: "Please select a PNG or JPEG image.",
      toastProcessError: "Failed to process image. Please try again.",
    },
    logoUploader: {
      label: "Project Logo",
      optional: "(Optional)",
      selectImage: "Select image",
      changeLogo: "Change logo",
      compressing: "Compressing...",
      remove: "Remove",
      hint: "PNG, JPEG (Drag and drop or select up to 1MB compressed)",
    },
    dangerZone: {
      title: "Danger Zone",
      description:
        "Permanently delete this project and all associated data. This action cannot be undone.",
      deleteButton: "Delete Project",
      deletingButton: "Deleting...",
      confirmTitle: "Delete Project",
      confirmDescription: "Are you sure you want to proceed?",
      confirmButton: "Delete Project",
    },
    settingsPage: {
      title: "Project Settings",
      description: "Update project settings or delete project.",
      accessDeniedTitle: "Access Denied",
      accessDeniedDescription:
        "You do not have permission to manage settings for this project.",
    },
    form: {
      nameLabel: "Project Name",
      namePlaceholder: "Enter project name",
      saveButton: "Save Changes",
      savingButton: "Saving...",
      uploadingButton: "Uploading logo...",
      cancelButton: "Cancel",
      toastUpdateSuccess: "Project updated successfully!",
      toastUpdateError: "Failed to update project",
      toastDeleteSuccess: "Project deleted successfully!",
      toastDeleteError: "Failed to delete project",
      toastUploadError: "Failed to upload logo.",
      toastUploadErrorRetry: "Failed to upload logo. Please try again.",
    },
  },

  // ─── Shared / Common ───────────────────────────────────────────
  common: {
    cancel: "Cancel",
    confirm: "Confirm",
    deletingFallback: "Deleting...",
    confirmingFallback: "Confirming...",
    and: "and",
  },
} as const;

export type AppCopy = typeof en;
